FROM nvidia/cuda:12.4.1-base-ubuntu22.04


RUN apt-get update -qq \
&& apt-get install -yqq \
python3.11 \
python3-pip && apt-get install -y git && \
rm -rf /var/lib/apt/lists/*

COPY ./api/ /app
WORKDIR /app

RUN pip install -U pip && pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]